"""Pin the vendored kinematics to the phi originals.

The fixture was generated by running phi's own modules. If our copy drifts --
by a stray edit, a bad merge, or a numpy behaviour change -- these fail.
"""

from __future__ import annotations

import sys
from typing import Any

import numpy as np
import pytest

from mirror.kinematics.forward import get_forward_kinematics
from mirror.kinematics.limits import JOINTS

from .conftest import PHI_SIM

#: The fixture came from the same code on the same numpy, so agreement should be
#: exact. Allowing 1e-15 covers summation-order differences across BLAS builds
#: without letting a real change through (a real change moves millimetres).
GOLDEN_TOL_M = 1e-15


def test_golden_fixture_is_self_describing(golden: dict[str, Any]) -> None:
    assert tuple(golden["joints"]) == JOINTS
    assert golden["q_deg"].shape[1] == 5
    assert golden["position"].shape == (golden["q_deg"].shape[0], 3)
    assert golden["rotation"].shape == (golden["q_deg"].shape[0], 3, 3)
    assert str(golden["phi_commit"]) == "66b919e"


def test_vendored_fk_reproduces_the_golden_positions(golden: dict[str, Any]) -> None:
    worst = 0.0
    for q, expected in zip(golden["q_deg"], golden["position"], strict=True):
        position, _ = get_forward_kinematics(dict(zip(JOINTS, q, strict=True), gripper=0.0))
        worst = max(worst, float(np.abs(position - expected).max()))
    assert worst <= GOLDEN_TOL_M, f"vendored FK drifted from phi by {worst:.3e} m"


def test_vendored_fk_reproduces_the_golden_rotations(golden: dict[str, Any]) -> None:
    worst = 0.0
    for q, expected in zip(golden["q_deg"], golden["rotation"], strict=True):
        _, rotation = get_forward_kinematics(dict(zip(JOINTS, q, strict=True), gripper=0.0))
        worst = max(worst, float(np.abs(rotation - expected).max()))
    assert worst <= GOLDEN_TOL_M, f"vendored FK rotation drifted from phi by {worst:.3e}"


def test_fk_rotations_in_the_fixture_are_valid(golden: dict[str, Any]) -> None:
    """A rotation that is not orthonormal would make every downstream stage lie."""
    for rotation in golden["rotation"]:
        assert np.abs(rotation.T @ rotation - np.eye(3)).max() < 1e-12
        assert np.linalg.det(rotation) == pytest.approx(1.0, abs=1e-12)


@pytest.mark.phi
def test_vendored_matches_phi_live_not_just_the_fixture() -> None:
    """Strongest form: import phi's module right now and compare, pose for pose."""
    if not PHI_SIM.exists():
        pytest.skip(f"phi not reachable at {PHI_SIM}")
    sys.path.insert(0, str(PHI_SIM))
    try:
        from so101_forward_kinematics import get_forward_kinematics as phi_fk
    finally:
        sys.path.remove(str(PHI_SIM))

    generator = np.random.default_rng(7)
    worst = 0.0
    for _ in range(200):
        q = dict(zip(JOINTS, generator.uniform(-90, 90, size=5), strict=True), gripper=0.0)
        ours, _ = get_forward_kinematics(q)
        theirs, _ = phi_fk(q)
        worst = max(worst, float(np.abs(ours - theirs).max()))
    assert worst == 0.0, f"vendored copy differs from live phi by {worst:.3e} m"
